### ISSUE TITLE
Angular Material/AngularJS conversion issue

### ISSUE THREAD

**Issue by bigosmallm** [BowlerHatLLC/dts2as#14]
I am trying to convert the Angular Material typescript definition file to a swc.  It has dependencies on AngularJS and JQuery.  I have attached the files I am using to this issue.  Here are the errors that I am encountering:

```
C:\p\flexroot\git\flex-asjs\examples\native\TodoMVC\lib>dts2as --flexHome "C:\Pr
ogram Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\sdks\flexjs_nightly_0.6.0" --
outSWC angularmaterial.swc angularmaterial.d.ts
C:\Users\omuppirala\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js:1712
            throw new Error("Return type " + this.getAS3FullyQualifiedNameFromTS
TypeNode(functionDeclaration.type) + " not found for method " + methodName + "()
 on type " + as3Type.getFullyQualifiedName() + ".");
            ^

Error: Return type ng.auto.IInjectorService not found for method resumeBootstrap
() on type angular.IAngularStatic.
    at TS2ASParser.populateMethod (C:\Users\omuppirala\AppData\Roaming\npm\node_
modules\dts2as\bin\parser.js:1712:19)
    at TS2ASParser.populateMember (C:\Users\omuppirala\AppData\Roaming\npm\node_
modules\dts2as\bin\parser.js:1530:26)
    at C:\Users\omuppirala\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js
:945:19
    at Array.forEach (native)
    at TS2ASParser.populateMembers (C:\Users\omuppirala\AppData\Roaming\npm\node
_modules\dts2as\bin\parser.js:944:17)
    at TS2ASParser.populateInterfaceMembers (C:\Users\omuppirala\AppData\Roaming
\npm\node_modules\dts2as\bin\parser.js:1234:14)
    at TS2ASParser.populatePackageLevelDefinitions (C:\Users\omuppirala\AppData\
Roaming\npm\node_modules\dts2as\bin\parser.js:911:26)
    at C:\Users\omuppirala\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js
:501:22
    at visitEachNode (C:\Users\omuppirala\AppData\Roaming\npm\node_modules\dts2a
s\node_modules\typescript\lib\typescript.js:7252:30)
    at Object.forEachChild (C:\Users\omuppirala\AppData\Roaming\npm\node_modules
\dts2as\node_modules\typescript\lib\typescript.js:7407:24)
```

Can you please take a look?

[angularmaterial.d.ts.txt](https://github.com/BowlerHatLLC/dts2as/files/191570/angularmaterial.d.ts.txt)
[jquery.d.ts.txt](https://github.com/BowlerHatLLC/dts2as/files/191568/jquery.d.ts.txt)
[angular.d.ts.txt](https://github.com/BowlerHatLLC/dts2as/files/191569/angular.d.ts.txt)

**Comment by joshtynjala** [comment]
This is a bug, and I can reproduce. dts2as doesn't currently know how to translate `ng.auto.IInjectorService` into `angular.auto.IInjectorService`. The `angular` module is imported as `ng`. If you manually change those references in the d.ts file to use `angular` instead of `ng`, you should be able to workaround this issue. I'm already handling some imports, but I guess this type is not among them. It should be something that I can fix in a future version of dts2as, though.

However, once you use the workaround, you're going to hit some other issues in angularmaterial.d.ts. It defines a number of properties that ActionScript doesn't support, such as properties that are numbers (like `4`, `100`, `200`, etc), and properties that have characters that are not allowed (like the hyphen in `hue-3`). In the TypeScript, `hue-3` is defined with quotes to get around the same rule in JavaScript, but ActionScript doesn't have a similar way to do that on a class or interface. The best that I can do to address this issue is to skip properties that cannot be translated and display a warning.

**Comment by bigosmallm** [comment]
> It should be something that I can fix in a future version of dts2as, though.

Rough idea when you would get a chance to fix it?

> but ActionScript doesn't have a similar way to do that on a class or interface.

I think that works fine in AS3? In fact, I am using it in a bunch of places today where the extern swc files don't have all the function/property definitions

For example:
`private var LIGHT_DEFAULT_HUES = {'accent':{'default':'A200', 'hue-1':'A100', 'hue-2':'A400', 'hue-3':'A700'}, 'background':{'default':'50', 'hue-1':'A100', 'hue-2':'100', 'hue-3':'300'}};
`
I can do this in AS3:
`panelTitle.style.backgroundColor = '#' + this.LIGHT_DEFAULT_HUES.background["hue-1"] + '00';`

Or calling a function like:
`public function createdCallback():void {

```
var sr = this['createShadowRoot']();

sr.innerHTML = 'This is a toolbar';
```

}`

**Comment by joshtynjala** [comment]
> Rough idea when you would get a chance to fix it?

I'm currently working on adding support for source maps in flex-falcon. That's going to take at least a couple more weeks. Maybe longer. If I find some time, I'll try to fit this in, but I really want to see in-browser debugging working soon!

> I think that works fine in AS3? In fact, I am using it in a bunch of places today where the extern swc files don't have all the function/property definitions

What I mean is that you can't define this style of properties/methods on a class/interface in ActionScript. It would need to look something like this to be useful for the compiler:

```
public interface MDThemeHues
{
    public var "hue-3":String;
}
```

Since that's not possible, dts2as needs to skip these properties, and possibly display a warning. It fails right now, but it can be fixed.

I forgot to mention, as a workaround for this one, you can simply remove those properties from the d.ts file.

**Comment by bigosmallm** [comment]
+1 for in browser debugging with source maps!

Okay, now I understand what you meant about the variable names.  I wonder if there is a way to replace a '-' with an '_' during the conversion?  It might still break, but it is slightly better than removing those properties.

**Comment by joshtynjala** [comment]
dts2as could do that, but the compiler wouldn't know to change it back. I think removing them is fine. To get/set properties like that in JS, they require ["hue-3"] syntax too. Honestly, I find it strange that this style was used in the first place, but I've not used this library, so I don't know the context.

**Comment by joshtynjala** [comment]
I fixed some issues, and passing angularmaterial.d.ts to dts2as will now produce a SWC without error.

I'll push a 0.9.0 update shortly!

**Comment by bigosmallm** [comment]
You are awesome!  Thanks :-)

**Comment by bigosmallm** [comment]
I grabbed the code and built 0.9.0 locally and tried it out.  It works!

**Comment by joshtynjala** [comment]
Great!
